name: Release

permissions:
  contents: write

on:
  push:
    branches: [main]
    paths: [README.md]

env:
  TEA_SECRET: ${{ secrets.TEA_SECRET }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: .github/mk-pantry-accessible.sh ${{ secrets.TEMP_JACOBS_GITHUB_PAT }}
      - uses: teaxyz/setup@v0.3.1 # TODO: major version only
      - id: rev-parse
        name: did we already publish this version?
        run: |
          # fetch tags since actions/checkout is a shallow checkout
          git fetch --prune --unshallow --tags

          if git show-ref --tags v$VERSION --quiet; then
            echo "::set-output name=result::cancel"
          fi

      - uses: andymckay/cancel-action@0.2
        if: ${{ steps.rev-parse.outputs.result == 'cancel' }}

  release:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v3
      - run: .github/mk-pantry-accessible.sh ${{ secrets.TEMP_JACOBS_GITHUB_PAT }}
      - uses: teaxyz/setup@v0.3.1 # TODO: major version only
      - run: | # Use on-box make until tea/pantry revlock is resolved
          sudo apt-get install \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-fonts-extra
          brew install \
            pandoc \
            pandoc-crossref \
            librsvg
      - run: |
          # Need a standard font, and ttf-mscorefonts-installer has a EULA dialog. Definitely #FIXME
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install texlive texlive-latex-extra texlive-xetex msttcorefonts #FIXME
      - name: Set Version
        run: |
          date=$(date '+%Y%m%d')
          echo "- \fancyfoot[L]{$VERSION}" >> metadata.yml
      # - run: tea make
      - run: make  # Use on-box make until tea/pantry revlock is resolved
      - uses: actions/upload-artifact@v3
        with:
          name: tea.white-paper
          path: |
            tea.white-paper.pdf
            tea.white-paper_??.pdf

      - name: Tag Release
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: |
            tea.white-paper.pdf
            tea.white-paper_??.pdf

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to S3
        run: |
          mkdir white-papers
          cp tea.white-paper.pdf tea.white-paper_??.pdf white-papers/
          aws s3 sync \
            ./white-papers s3://www.tea.xyz/ \
            --metadata-directive REPLACE \
            --cache-control no-cache,must-revalidate
      - name: Invalidate cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CF_DISTRIBUTION_ID }} \
            --paths / /tea.white-paper*.pdf
